# Generated by Django 5.0 on 2023-12-12 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место привычки')),
                ('time', models.TimeField(verbose_name='Время')),
                ('activity', models.CharField(verbose_name='Действие')),
                ('sign_of_a_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная'), ('monthly', 'Ежемесячная')], default='daily', max_length=100, verbose_name='Периодичность')),
                ('reward', models.TextField(verbose_name='Вознаграждение')),
                ('duration_of_action', models.IntegerField(verbose_name='Длительность привычки в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности привычки')),
                ('last_reminder', models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
