# Generated by Django 4.2.8 on 2023-12-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_rename_habits_habit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='activity',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='sign_of_a_pleasant_habit',
            new_name='is_pleasant',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='frequency',
            new_name='period',
        ),
    ]
