# Generated by Django 4.2.8 on 2023-12-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_activity_habit_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='associated_habit',
            new_name='connected_habit',
        ),
    ]
