# Generated by Django 4.2.8 on 2023-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.TextField(blank=True, null=True, verbose_name='Вознаграждение'),
        ),
    ]
